### ISSUE TITLE
[Proposal] composer install --no-dev when prod environment

### ISSUE THREAD

**Issue by ablunier** [anavallasuiza/laravel-Admin#1]
Maybe would be useful if the `composer install` command executes with the `--no-dev` option when we are on a production environment.

We could use the `APP_DEBUG` or `APP_ENV` environment variable to implement this condition here: https://github.com/anavallasuiza/laravel-Admin/blob/develop/src/anavallasuiza/laravel-Admin/Http/Processors/Management/Update.php#L60

What do you think about this @eusonlito ?

**Comment by eusonlito** [comment]
Maybe an `COMPOSER_OPTIONS=` at `.env`.

I have some environments with more than 2 installations, and each one has a different `APP_ENV` and I some times have enabled `APP_DEBUG` to check issues. Then I think that a new option is the best solution.

I'm adding also a `git branch` option to admin area.

**Comment by ablunier** [comment]
:+1:

**Comment by eusonlito** [comment]
Done!
